import java.util.Vector;
class Main{
public static void main(String args[]){
Vector<String>grocery=new Vector<>();
Vector<String>fruits=new Vector<>();
fruits.add("mango");
fruits.add("apple");
fruits.add("grapes");
fruits.add("banana");
fruits.add("berries");
fruits.add("citrus");
 Vector<String>Fruits=new Vector<>();
Fruits.add("peaches");
Fruits.add("coconut");
Fruits.add("pears");
Fruits.add("pineapple");
Fruits.addAll(fruits);
System.out.println("New Vector:"+Fruits);
Vector<String>vegetables=new Vector<>();
vegetables.add("onions");
vegetables.add("tomato");
vegetables.add("chillies");
vegetables.add("ginger");
vegetables.add("garlic");
vegetables.add("potato");
vegetables.add("peppers");
vegetables.add("broccoli");
vegetables.add("carrot");
vegetables.add("cabbage");
System.out.println("New Vector:"+vegetables);
Vector<String>AnimalProduce=new Vector<>();
AnimalProduce.add("chicken");
AnimalProduce.add("meat");
AnimalProduce.add("fish");
AnimalProduce.add("eggs");
System.out.println("New Vector:"+AnimalProduce);
Vector<String>DiaryProducts=new Vector<>();
DiaryProducts.add("milk");
DiaryProducts.add("eggs");
DiaryProducts.add("cheese");
DiaryProducts.add("butter");
DiaryProducts.add("yogurt");
DiaryProducts.add("ghee");
System.out.println("New Vector:"+DiaryProducts);
Vector<String>BakeryProducts=new Vector<>();
BakeryProducts.add("Whole_Wheat_Bread");
BakeryProducts.add("kulchas");
BakeryProducts.add("bakery_buns");
BakeryProducts.add("biscuits");
BakeryProducts.add("cakes");
System.out.println("New Vector:"+BakeryProducts);
Vector<String>condiments=new Vector<>();
condiments.add("salt"); 
condiments.add("pepper");
condiments.add("sugar");
System.out.println("New Vector:"+condiments);
Vector<String>spices=new Vector<>();
spices.add("cardamom");
spices.add("cinnamon");
spices.add("nutmeg");
spices.add("zeera");
spices.add("ajwain");
spices.add("turmeric");
System.out.println("New Vector:"+spices);
Vector<String>oils_sauces=new Vector<>();
oils_sauces.add("olive_oil");
oils_sauces.add("mustard_oil");
oils_sauces.add("sunflower_oil");
oils_sauces.add("Soy_souce");
oils_sauces.add("fish_souce");
oils_sauces.add("venigar");
oils_sauces.add("tomato_ketchup");
System.out.println("New Vector:"+oils_sauces);
Vector<String>cleaningsupplies=new Vector<>();
cleaningsupplies.add("dishwasher_soap");
cleaningsupplies.add("detergent_powder");
cleaningsupplies.add("shaving_cream");
cleaningsupplies.add("toilet_cleaner");
cleaningsupplies.add("cleaner");
 
System.out.println("New Vector:"+cleaningsupplies);
Vector<String> GrainLugumes=new Vector<>();
GrainLugumes.add("atta");
GrainLugumes.add("rice");
GrainLugumes.add("pasta");
GrainLugumes.add("butter");
GrainLugumes.add("yogurt");
GrainLugumes.add("ghee");
System.out.println("new vector:"+GrainLugumes);
}
}